security:
    # Désactivation du hachage : comparaison en clair
    password_hashers:
        # Pour toutes les classes implémentant PasswordAuthenticatedUserInterface
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: plaintext
        # Spécifiquement pour votre entité User
        App\Entity\User:
            algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/dashboard, roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/employee, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/user/settings, roles: ROLE_USER }
        - { path: ^/travel-request, roles: ROLE_USER }
        - { path: ^/expense, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

# Configuration pour les tests (inchangée, si vous utilisez toujours un hasher « light » en test)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
